indent-width = 2
line-length = 120
preview = true
required-version = '>=0.15.2'
respect-gitignore = false
target-version = 'py313'

[format]
docstring-code-format = true
quote-style = 'single'
preview = true

[lint]
select = ['ALL']
ignore = [
  'COM812',
  'CPY001',
  'D100',
  'D101',
  'D102',
  'D103',
  'D104',
  'D105',
  'D106',
  'D107',
  'E111',
  'E114',
  'G004',
  'Q002',
  'T20',
]
preview = true

[lint.flake8-quotes]
docstring-quotes = 'single'
inline-quotes = 'single'

[lint.pydocstyle]
convention = 'google'
